import type { EducationEntry, ExperienceEntry } from "@/types";

/**
 * About page copy. No history is invented here: the education and experience
 * records state only facts the author has supplied, and the experience list is
 * academic rather than employment, because no professional roles exist yet.
 */
export const ABOUT_HEADER = {
  title: "About",
  description:
    "An IT student specializing in cybersecurity, working mostly on the server side — secure backends, database design, and the systems that hold them together.",
} as const;

export const ABOUT_PROFILE = {
  title: "Professional profile",
  description: "Who I am, how I work, and where I am heading.",
  /** Ordered narrative: who, background, how they work, where they are headed. */
  entries: [
    {
      heading: "Introduction",
      body: "I am a fourth-year BS Information Technology student at Mapúa Malayan Colleges Laguna, specializing in Cybersecurity and working backend-first. My interest is in the parts of a system most users never see: the API boundaries, the data model underneath, and the middleware that lets separate components exchange data reliably. This portfolio presents systems work rather than interface work.",
    },
    {
      heading: "Professional background",
      body: "My experience combines academic software engineering with enterprise information security. The academic side spans backend and API development, relational database design, and the integration of embedded devices, mobile clients, and web services into systems that had to run as a whole. On the security side, I served as an Information Security intern at Datamatics Philippines, assigned to the IT Security team under its ISMS function, where I reviewed SIEM logs, monitored endpoints, and contributed to compliance documentation in a live enterprise environment.",
    },
    {
      heading: "Engineering philosophy",
      body: "I treat structure as the deliverable. A system is finished when its boundaries are clear, its data model holds its own invariants, and the next person can change it without reading every file first — not when the feature happens to work. I prefer explicit, readable implementations over clever ones, and I would rather spend the time on schema design and interface contracts up front than debug the consequences of skipping them. Security reinforced this: reviewing real incidents taught me that most failures trace back to a decision that seemed harmless at the time.",
    },
    {
      heading: "Career objectives",
      body: "I am working toward backend and systems engineering roles where the problems are architectural — designing services, data pipelines, and the integration layers between them — and where security is a design input rather than a later audit. In the near term I am looking for engineering work that puts me close to production systems and their data. Longer term, I am aiming at data engineering and platform or infrastructure work, building on the backend and security foundation I am developing now.",
    },
  ],
} as const;

export const ABOUT_EXPERIENCE = {
  title: "Professional experience",
  description:
    "Applied information security practice in an enterprise environment.",
  /** Reverse-chronological. */
  entries: [
    {
      role: "Information Security Intern",
      organization: "Datamatics Philippines",
      duration: "2026",
      summary:
        "Assigned to the IT Security team under the Information Security Management System (ISMS) function. Reviewed and audited daily security logs from the organization's SIEM platform, engaged in the Threat Intelligence Process (TIP), and referenced internal playbooks to identify anomalies. Monitored endpoint activity and malware alerts, investigating and documenting findings generated by SentinelOne and OpenVAS, and assisted in vulnerability scanning and reporting aligned to NIST incident response and vulnerability management frameworks. Contributed to monthly desktop auditing — verifying SentinelOne agent versions, checking audit compliance, and handling frontline diagnostics such as outdated clients, agents disconnected from the central console, and network interruptions caused by SentinelOne blocking traffic in response to malware detections. Observed and assisted in firewall configuration and monitoring, supporting traffic filtering, policy review, and threat visibility. In Governance, Risk, and Compliance, helped maintain ISMS documentation and assisted with reporting for ISO 27001:2022, PCI DSS, and SOC 2 Type II; proofread and edited information security policies and prepared evidence for internal audits. Designed cyber warfare infographics for internal awareness campaigns and regularly led ISMS presentations in the supervisor's absence.",
    },
    {
      role: "Work Immersion, IT Documentation Lead",
      organization: "CREOTEC",
      duration: "2022",
      summary:
        "Developed Android-based applications backed by server-side services to support business operations, including tools for payroll automation, internal monitoring, and departmental workflows.",
    },
  ] satisfies ExperienceEntry[],
} as const;

/**
 * Summary of undergraduate engineering experience. Prose, not a project list:
 * the Projects page is the source of truth for individual projects, so no
 * project is named here and the section closes by pointing readers there.
 */
export const ABOUT_ACADEMIC = {
  title: "Academic engineering experience",
  description:
    "The engineering ground covered across four years of undergraduate project work.",
  paragraphs: [
    "Across four years of undergraduate coursework and project work, most of my engineering happened on the server side. I designed and built RESTful backends — front-controller routing, PDO-based data access layers, and secure CRUD operations with paginated retrieval — over normalized relational schemas built to hold their own invariants. Relational database design and clear API contracts were where I spent the most deliberate effort.",
    "That backend work rarely stood alone. I integrated separate components into systems that had to run as a whole, connecting embedded devices such as Raspberry Pi probes and Wemos D1 microcontrollers, along with Android and web clients, to server-side services — and writing the middleware and firmware on both sides of the device-to-server boundary. The same period covered mobile and web application development across several stacks, and embedded work close to the hardware.",
    "Cybersecurity is my specialization, and it shaped how I approached even projects where security was not the point, treating input handling, data exposure, and access as design inputs rather than later fixes. Much of the work was collaborative, and I led teams as often as I contributed to them — coordinating tasks and carrying systems from concept to delivery. Representative engineering work is documented in the Projects section.",
  ],
} as const;

export const ABOUT_EDUCATION = {
  title: "Education",
  description: "Academic background and specialization.",
  entries: [
    {
      degree: "Bachelor of Science in Information Technology, Cybersecurity Specialization",
      institution: "Mapúa Malayan Colleges Laguna",
      year: "2022 — 2026 (expected)",
      description:
        "Consistent Dean's Lister. Coursework spans backend development, database design, networking, and security analysis; capstone work centers on a Raspberry Pi-based Wi-Fi security assessment platform.",
    },
    {
      degree: "Science, Technology, Engineering, and Mathematics (STEM) Strand",
      institution: "Santa Rosa Science and Technology High School",
      year: "2016 — 2022",
      description: "Graduated With High Honors.",
    },
  ] satisfies EducationEntry[],
} as const;

/**
 * Contextual framing only. The full inventory lives on the Skills page and is
 * deliberately not duplicated here.
 */
export const ABOUT_TECHNOLOGIES = {
  title: "Technologies",
  description: "The areas of the stack I work in, at a high level.",
  body: "My work sits mainly on the server side: PHP, C#, and Python for application and API logic, MySQL and Supabase for data, and XAMPP, Railway, and Raspberry Pi as the environments they run on. I reach for tools that fit the constraints of the system rather than the newest option — a PDO data access layer and a normalized schema solve most of what an academic project actually needs. Security tooling from my internship (Wazuh, SentinelOne, OpenVAS, FortiGate) sits alongside this rather than replacing it. The complete inventory is on the Skills page.",
  action: { label: "View all skills", href: "/skills" },
} as const;

export const ABOUT_CTA = {
  title: "See the work",
  description:
    "The projects below show how this background translates into delivered systems.",
  action: { label: "View projects", href: "/projects" },
} as const;
